### ISSUE TITLE
About Me相关

### ISSUE THREAD

**Issue by miawang96** [gaoryrt/blog#1]
你好，你的About Me界面特别有创意，我也很想尝试一下，看了你的源码，还是有点迷惑，可以请教一下你大致的开发思路吗？

**Comment by gaoryrt** [comment]
没有开源，光看源码肯定看不出什么东西的……

可变字体、svg textPath、平滑滚动、视差、背景混合的缝合怪而已。

credits to:

**Comment by miawang96** [comment]
> 没有开源，光看源码肯定看不出什么东西的……
> 
> 可变字体、svg textPath、平滑滚动、视差、背景混合的缝合怪而已。
> 
> credits to:
> https://www.recursive.design/
> https://editorialnew.com/
> https://github.com/gaoryrt/cursor-dot
> https://css-tricks.com/moving-text-on-a-curved-path/
> [www.youtube.com/watch?v=jk6sz25OZgw](http://www.youtube.com/watch?v=jk6sz25OZgw)

**Comment by miawang96** [comment]
多谢~提前预祝假期愉快 ；-）

**Comment by gaoryrt** [comment]
也祝你节日快乐
